# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Cours"
  pageRef = "cours"
  weight = 10

[[main]]
  name = "Plan du cours"
  parent = "Cours"
  pageRef = "cours/plan-cours"
  weight = 10

[[main]]
  name = "Glossaire"
  parent = "Cours"
  pageRef = "cours/glossaire"
  weight = 20

[[main]]
  name = "Syllabus"
  pageRef = "syllabus"
  weight = 20

[[main]]
  name = "A propos"
  pageRef = "a_propos"
  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "INFN Poitiers"
  pageRef = "https://www.infn.fr/sites-enseignement/poitiers/"
  weight = 10
