services:
  hugo:
    image: floryn90/hugo
    user: ${DOCKER_USER:-1000}
    command: server -D
    ports:
      - "1313:1313"
    volumes:
      - .:/src

  prettier:
    image: tmknom/prettier
    user: ${DOCKER_USER:-1000}
    volumes:
      - .:/work
